image:
  repository: quay.io/presslabs/wordpress-load-tests
  tag: latest
  pullPolicy: Always

influxdb_url: http://storage-influxdb.default.svc.cluster.local:8086/k6

scenario:
  name: main
  url: http://dev-stack.trypl.com/
  vus: "500"
  duration: 300s
  # tag: simpel-test
  # cache_bypass_param: ?nocache
  # product_url: /product/fiery-valiant-moth-of-painting/
  # product_id: 5177
  # checkout_url: /checkout/

# resources:
#   requests:
#     cpu: "14"
#     memory: "90Gi"
#   limits:
#     cpu: "15"
#     memory: "100Gi"
