image:
  repository: quay.io/presslabs/wordpress-load-tests
  tag: latest
  pullPolicy: Always

influxdb_url: http://storage-influxdb.default.svc.cluster.local:8086/k6

scenario:
  url: http://test.loadimpact.com/
  vus: "500"
  duration: 300s
  cache_bypass_param: ?nocache
  name: main

# resources:
#   requests:
#     cpu: "14"
#     memory: "90Gi"
#   limits:
#     cpu: "15"
#     memory: "100Gi"
