image:
  repository: quay.io/presslabs/wordpress-load-tests
  tag: latest
  pullPolicy: IfNotPresent

influxdb_url: http://storage-influxdb.default.svc.cluster.local:8086/k6

scenario:
  url: https://test.loadimpact.com
  vus: "50"
  duration: 300s
