version: '3'

services:
  k6:
    image: loadimpact/k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
      - CASES_URL=http://test.loadimpact.com/
      - CASES_VUs=1000
      - CASES_DURATION=300s
    command: run /var/lib/k6/main.js
    volumes:
      - ./tests/:/var/lib/k6/
  influxdb:
    build:
      context: .
      dockerfile: Dockerfile.influxdb
    ports:
      - "8086:8086"
  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    links:
      - influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - "3000:3000"
